2024-03-14 08:32:06.602 UTC [5062] LOG:  starting PostgreSQL 16.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 12.3.0-5) 12.3.0, 64-bit
2024-03-14 08:32:06.603 UTC [5062] LOG:  listening on IPv6 address "::1", port 5432
2024-03-14 08:32:06.603 UTC [5062] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-03-14 08:32:06.620 UTC [5062] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-03-14 08:32:06.645 UTC [5065] LOG:  database system was shut down at 2024-03-14 08:32:00 UTC
2024-03-14 08:32:06.661 UTC [5062] LOG:  database system is ready to accept connections
2024-03-14 08:32:16.258 UTC [5160] FATAL:  database "db" does not exist
2024-03-14 08:32:49.920 UTC [5323] ERROR:  relation "widgets" does not exist
2024-03-14 08:32:49.920 UTC [5323] STATEMENT:  CREATE TABLE reports (
	    widget_id INT REFERENCES widgets(widget_id),
	    reports_id SERIAL PRIMARY KEY,
	    create_dttm TIMESTAMP NOT NULL,
	    filepath JSON,
	    period_flag BOOLEAN,
	    report_text JSON
	);
2024-03-14 08:37:06.724 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 08:38:43.037 UTC [5063] LOG:  checkpoint complete: wrote 955 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=95.223 s, sync=1.027 s, total=96.313 s; sync files=336, longest=0.014 s, average=0.004 s; distance=4407 kB, estimate=4407 kB; lsn=0/18CE458, redo lsn=0/18CE420
2024-03-14 09:01:50.373 UTC [17077] ERROR:  column "id" does not exist at character 182
2024-03-14 09:01:50.373 UTC [17077] STATEMENT:  INSERT INTO "widgets" ("user_id", "widget_name", "key_words", "sources_id", "schedule_hour") VALUES (1, 'Weather Widget', ARRAY['weather','forecast'], ARRAY['1','2'], 14) RETURNING "id";
2024-03-14 09:03:04.158 UTC [17566] ERROR:  column "id" does not exist at character 182
2024-03-14 09:03:04.158 UTC [17566] STATEMENT:  INSERT INTO "widgets" ("user_id", "widget_name", "key_words", "sources_id", "schedule_hour") VALUES (1, 'Weather Widget', ARRAY['weather','forecast'], ARRAY['1','2'], 14) RETURNING "id";
2024-03-14 09:03:25.877 UTC [17748] ERROR:  column "id" does not exist at character 63
2024-03-14 09:03:25.877 UTC [17748] STATEMENT:  INSERT INTO "users" ("username") VALUES ('johndoe') RETURNING "id";
2024-03-14 09:09:46.742 UTC [20257] ERROR:  column "id" does not exist at character 63
2024-03-14 09:09:46.742 UTC [20257] STATEMENT:  INSERT INTO "users" ("username") VALUES ('johndoe') RETURNING "id";
2024-03-14 09:12:06.658 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:12:07.381 UTC [5063] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.617 s, sync=0.034 s, total=0.724 s; sync files=6, longest=0.014 s, average=0.006 s; distance=0 kB, estimate=3966 kB; lsn=0/18CE7D8, redo lsn=0/18CE7A0
2024-03-14 09:13:19.950 UTC [21716] ERROR:  column "id" does not exist at character 63
2024-03-14 09:13:19.950 UTC [21716] STATEMENT:  INSERT INTO "users" ("username") VALUES ('johndoe') RETURNING "id";
2024-03-14 09:17:06.476 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:17:06.875 UTC [5063] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.311 s, sync=0.026 s, total=0.399 s; sync files=4, longest=0.015 s, average=0.007 s; distance=0 kB, estimate=3570 kB; lsn=0/18CEB00, redo lsn=0/18CEAC8
2024-03-14 09:21:32.232 UTC [24953] ERROR:  column "user_id" does not exist at character 210
2024-03-14 09:21:32.232 UTC [24953] STATEMENT:  INSERT INTO "reports" ("widget_id", "create_dttm", "filepath", "period_flag", "report_text") VALUES (1, '2024-01-01 00:00:00', '{"path": "path/to/file"}', true, '{"content": "Report content here"}') RETURNING "user_id";
2024-03-14 09:21:45.081 UTC [25070] ERROR:  column "user_id" does not exist at character 210
2024-03-14 09:21:45.081 UTC [25070] STATEMENT:  INSERT INTO "reports" ("widget_id", "create_dttm", "filepath", "period_flag", "report_text") VALUES (1, '2024-01-01 00:00:00', '{"path": "path/to/file"}', true, '{"content": "Report content here"}') RETURNING "user_id";
2024-03-14 09:22:06.972 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:22:08.194 UTC [5063] LOG:  checkpoint complete: wrote 12 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.113 s, sync=0.048 s, total=1.222 s; sync files=11, longest=0.014 s, average=0.005 s; distance=10 kB, estimate=3214 kB; lsn=0/18D14D0, redo lsn=0/18D1498
2024-03-14 09:27:06.292 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:27:06.693 UTC [5063] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.312 s, sync=0.027 s, total=0.402 s; sync files=4, longest=0.012 s, average=0.007 s; distance=1 kB, estimate=2892 kB; lsn=0/18D1B48, redo lsn=0/18D1B10
2024-03-14 09:32:06.793 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:32:09.447 UTC [5063] LOG:  checkpoint complete: wrote 26 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.525 s, sync=0.073 s, total=2.655 s; sync files=22, longest=0.013 s, average=0.004 s; distance=6 kB, estimate=2604 kB; lsn=0/18D34C0, redo lsn=0/18D3488
2024-03-14 09:37:06.543 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:37:08.169 UTC [5063] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.513 s, sync=0.058 s, total=1.626 s; sync files=16, longest=0.013 s, average=0.004 s; distance=5 kB, estimate=2344 kB; lsn=0/18D49C0, redo lsn=0/18D4988
2024-03-14 09:40:29.320 UTC [32351] ERROR:  update or delete on table "users" violates foreign key constraint "widgets_user_id_fkey" on table "widgets"
2024-03-14 09:40:29.320 UTC [32351] DETAIL:  Key (user_id)=(1) is still referenced from table "widgets".
2024-03-14 09:40:29.320 UTC [32351] STATEMENT:  DELETE FROM "users" 
2024-03-14 09:42:06.241 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:42:06.744 UTC [5063] LOG:  checkpoint complete: wrote 5 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.413 s, sync=0.027 s, total=0.504 s; sync files=5, longest=0.013 s, average=0.006 s; distance=3 kB, estimate=2110 kB; lsn=0/18D57E8, redo lsn=0/18D57B0
2024-03-14 09:47:06.834 UTC [5063] LOG:  checkpoint starting: time
2024-03-14 09:47:08.469 UTC [5063] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.520 s, sync=0.057 s, total=1.635 s; sync files=16, longest=0.014 s, average=0.004 s; distance=6 kB, estimate=1899 kB; lsn=0/18D7140, redo lsn=0/18D7108
2024-03-18 19:07:41.133 UTC [82976] LOG:  starting PostgreSQL 16.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 12.3.0-5) 12.3.0, 64-bit
2024-03-18 19:07:41.137 UTC [82976] LOG:  listening on IPv6 address "::1", port 5432
2024-03-18 19:07:41.137 UTC [82976] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-03-18 19:07:41.156 UTC [82976] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-03-18 19:07:41.197 UTC [82990] LOG:  database system was interrupted; last known up at 2024-03-14 09:47:08 UTC
2024-03-18 19:07:46.361 UTC [82990] LOG:  database system was not properly shut down; automatic recovery in progress
2024-03-18 19:07:46.388 UTC [82990] LOG:  redo starts at 0/18D7108
2024-03-18 19:07:46.388 UTC [82990] LOG:  invalid record length at 0/18D71F0: expected at least 24, got 0
2024-03-18 19:07:46.388 UTC [82990] LOG:  redo done at 0/18D71B8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-03-18 19:07:46.423 UTC [82988] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-03-18 19:07:46.543 UTC [82988] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.031 s, sync=0.015 s, total=0.138 s; sync files=2, longest=0.008 s, average=0.008 s; distance=0 kB, estimate=0 kB; lsn=0/18D71F0, redo lsn=0/18D71F0
2024-03-18 19:07:46.564 UTC [82976] LOG:  database system is ready to accept connections
2024-03-18 19:12:46.644 UTC [82988] LOG:  checkpoint starting: time
2024-03-18 19:12:48.744 UTC [82988] LOG:  checkpoint complete: wrote 20 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.919 s, sync=0.091 s, total=2.100 s; sync files=18, longest=0.022 s, average=0.006 s; distance=12 kB, estimate=12 kB; lsn=0/18DA308, redo lsn=0/18DA2D0
2024-03-18 19:58:38.213 UTC [3869] LOG:  starting PostgreSQL 16.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 12.3.0-5) 12.3.0, 64-bit
2024-03-18 19:58:38.217 UTC [3869] LOG:  listening on IPv6 address "::1", port 5432
2024-03-18 19:58:38.217 UTC [3869] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-03-18 19:58:38.234 UTC [3869] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-03-18 19:58:38.276 UTC [3872] LOG:  database system was interrupted; last known up at 2024-03-18 19:12:48 UTC
2024-03-18 19:58:43.376 UTC [3872] LOG:  database system was not properly shut down; automatic recovery in progress
2024-03-18 19:58:43.397 UTC [3872] LOG:  redo starts at 0/18DA2D0
2024-03-18 19:58:43.397 UTC [3872] LOG:  invalid record length at 0/18DA3B8: expected at least 24, got 0
2024-03-18 19:58:43.397 UTC [3872] LOG:  redo done at 0/18DA380 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-03-18 19:58:43.441 UTC [3870] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-03-18 19:58:43.564 UTC [3870] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.031 s, sync=0.015 s, total=0.149 s; sync files=2, longest=0.008 s, average=0.008 s; distance=0 kB, estimate=0 kB; lsn=0/18DA3B8, redo lsn=0/18DA3B8
2024-03-18 19:58:43.585 UTC [3869] LOG:  database system is ready to accept connections
2024-03-18 20:03:43.657 UTC [3870] LOG:  checkpoint starting: time
2024-03-18 20:03:45.371 UTC [3870] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.522 s, sync=0.084 s, total=1.714 s; sync files=16, longest=0.020 s, average=0.006 s; distance=7 kB, estimate=7 kB; lsn=0/18DC048, redo lsn=0/18DBFF8
2024-03-19 18:03:29.478 UTC [22609] LOG:  starting PostgreSQL 16.2 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 12.3.0-5) 12.3.0, 64-bit
2024-03-19 18:03:29.482 UTC [22609] LOG:  listening on IPv6 address "::1", port 5432
2024-03-19 18:03:29.482 UTC [22609] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-03-19 18:03:29.500 UTC [22609] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-03-19 18:03:29.552 UTC [22612] LOG:  database system was interrupted; last known up at 2024-03-18 20:03:45 UTC
2024-03-19 18:03:34.645 UTC [22612] LOG:  database system was not properly shut down; automatic recovery in progress
2024-03-19 18:03:34.663 UTC [22612] LOG:  redo starts at 0/18DBFF8
2024-03-19 18:03:34.663 UTC [22612] LOG:  invalid record length at 0/18DC0F8: expected at least 24, got 0
2024-03-19 18:03:34.663 UTC [22612] LOG:  redo done at 0/18DC0C0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-03-19 18:03:34.699 UTC [22610] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-03-19 18:03:34.818 UTC [22610] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.029 s, sync=0.015 s, total=0.134 s; sync files=2, longest=0.008 s, average=0.008 s; distance=0 kB, estimate=0 kB; lsn=0/18DC0F8, redo lsn=0/18DC0F8
2024-03-19 18:03:34.837 UTC [22609] LOG:  database system is ready to accept connections
2024-03-19 18:08:34.919 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:08:36.607 UTC [22610] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.519 s, sync=0.081 s, total=1.689 s; sync files=16, longest=0.020 s, average=0.006 s; distance=8 kB, estimate=8 kB; lsn=0/18DE458, redo lsn=0/18DE420
2024-03-19 18:18:34.761 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:18:35.506 UTC [22610] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.616 s, sync=0.045 s, total=0.745 s; sync files=7, longest=0.020 s, average=0.007 s; distance=4 kB, estimate=8 kB; lsn=0/18DF5F8, redo lsn=0/18DF5C0
2024-03-19 18:28:34.697 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:28:36.383 UTC [22610] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.518 s, sync=0.081 s, total=1.687 s; sync files=16, longest=0.023 s, average=0.006 s; distance=8 kB, estimate=8 kB; lsn=0/18E1990, redo lsn=0/18E1958
2024-03-19 18:38:34.569 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:38:36.253 UTC [22610] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.519 s, sync=0.080 s, total=1.684 s; sync files=16, longest=0.022 s, average=0.005 s; distance=9 kB, estimate=9 kB; lsn=0/18E4118, redo lsn=0/18E40E0
2024-03-19 18:48:34.430 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:48:36.120 UTC [22610] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.518 s, sync=0.084 s, total=1.691 s; sync files=16, longest=0.022 s, average=0.006 s; distance=11 kB, estimate=11 kB; lsn=0/18E6EB0, redo lsn=0/18E6E78
2024-03-19 18:58:34.319 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 18:58:34.585 UTC [22610] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.120 s, sync=0.025 s, total=0.266 s; sync files=2, longest=0.018 s, average=0.013 s; distance=4 kB, estimate=10 kB; lsn=0/18E7F38, redo lsn=0/18E7F00
2024-03-19 19:00:35.150 UTC [45085] ERROR:  syntax error at or near "=" at character 32
2024-03-19 19:00:35.150 UTC [45085] STATEMENT:  SELECT * FROM "users" username = 'johndoe'
2024-03-19 19:02:01.451 UTC [45659] ERROR:  syntax error at or near "=" at character 32
2024-03-19 19:02:01.451 UTC [45659] STATEMENT:  SELECT * FROM "users" username = 'johndoe'
2024-03-19 19:02:42.913 UTC [46075] ERROR:  syntax error at or near "=" at character 32
2024-03-19 19:02:42.913 UTC [46075] STATEMENT:  SELECT * FROM "users" username = 'johndoe'
2024-03-19 19:03:34.683 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 19:03:36.364 UTC [22610] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.519 s, sync=0.078 s, total=1.681 s; sync files=16, longest=0.018 s, average=0.005 s; distance=15 kB, estimate=15 kB; lsn=0/18EBD70, redo lsn=0/18EBD38
2024-03-19 19:05:10.400 UTC [47034] ERROR:  syntax error at or near "=" at character 32
2024-03-19 19:05:10.400 UTC [47034] STATEMENT:  SELECT * FROM "users" username = 'johndoe'
2024-03-19 19:05:12.032 UTC [47064] ERROR:  syntax error at or near "=" at character 32
2024-03-19 19:05:12.032 UTC [47064] STATEMENT:  SELECT * FROM "users" username = 'johndoe'
2024-03-19 19:05:56.333 UTC [47401] ERROR:  syntax error at or near "WHERE" at character 53
2024-03-19 19:05:56.333 UTC [47401] STATEMENT:  UPDATE "users" SET "username" = 'newusername' WHERE WHERE username = 'johndoe'
2024-03-19 19:06:24.857 UTC [47619] ERROR:  column "report_id" does not exist at character 84
2024-03-19 19:06:24.857 UTC [47619] HINT:  Perhaps you meant to reference the column "reports.reports_id".
2024-03-19 19:06:24.857 UTC [47619] STATEMENT:  UPDATE "reports" SET "report_text" = '{"content": "Updated report content"}' WHERE report_id = 1
2024-03-19 19:08:34.464 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 19:08:34.792 UTC [22610] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.215 s, sync=0.028 s, total=0.329 s; sync files=3, longest=0.017 s, average=0.010 s; distance=3 kB, estimate=14 kB; lsn=0/18ECA20, redo lsn=0/18EC9E8
2024-03-19 19:09:42.420 UTC [48955] ERROR:  column "report_id" does not exist at character 84
2024-03-19 19:09:42.420 UTC [48955] HINT:  Perhaps you meant to reference the column "reports.reports_id".
2024-03-19 19:09:42.420 UTC [48955] STATEMENT:  UPDATE "reports" SET "report_text" = '{"content": "Updated report content"}' WHERE report_id = 1
2024-03-19 19:11:07.945 UTC [49563] ERROR:  column "report_id" does not exist at character 84
2024-03-19 19:11:07.945 UTC [49563] HINT:  Perhaps you meant to reference the column "reports.reports_id".
2024-03-19 19:11:07.945 UTC [49563] STATEMENT:  UPDATE "reports" SET "report_text" = '{"content": "Updated report content"}' WHERE report_id = 1
2024-03-19 19:13:34.889 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 19:13:35.230 UTC [22610] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.218 s, sync=0.028 s, total=0.342 s; sync files=3, longest=0.017 s, average=0.010 s; distance=6 kB, estimate=13 kB; lsn=0/18EE3B8, redo lsn=0/18EE380
2024-03-19 19:18:34.315 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 19:18:34.649 UTC [22610] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.216 s, sync=0.028 s, total=0.334 s; sync files=3, longest=0.017 s, average=0.010 s; distance=6 kB, estimate=12 kB; lsn=0/18EFDA0, redo lsn=0/18EFD68
2024-03-19 19:28:34.845 UTC [22610] LOG:  checkpoint starting: time
2024-03-19 19:28:35.164 UTC [22610] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.216 s, sync=0.029 s, total=0.320 s; sync files=3, longest=0.018 s, average=0.010 s; distance=6 kB, estimate=12 kB; lsn=0/18F1890, redo lsn=0/18F1858
